DROP TABLE IF EXISTS example;

CREATE TABLE example(
id INTEGER,
NAME TEXT,
age INTEGER,
marks INTEGER
);

INSERT INTO example VALUES(1,'HERAMBHA',18,90);
INSERT INTO example VALUES(2,'KARTHIKEYA',19,87);
INSERT INTO example VALUES(3,'GUPTHA',17,93);
INSERT INTO example VALUES(4,'ESWARA RAO',22,96);
INSERT INTO example VALUES(5,'GAYATHRI',24,98);
INSERT INTO example VALUES(6,'NAMRATHA',16,100);

SELECT * FROM example;
